### ISSUE TITLE
Is `cond_samp` correct for `mode = 'score'`?

### ISSUE THREAD

**Issue by wiep** [katzfuss-group/BaTraMaSpa_py#1]
@JCatwood, @danjdrennan, @jiayilei, how sure are you that the function [cond_samp](https://github.com/katzfuss-group/BaTraMaSpa_py/blob/d75974961317a5b1e30d6f2fcc14862e1cb0535b/fit_map.py#L221) does the same as the R function [condSamp](https://github.com/katzfuss-group/BaTraMaSpa/blob/af2b4a45bdaf0efa8908d8abf1fa32d7a39e6005/code/nonlinearSpatial_functions.R#L267) when set mode = 'score'? Or -- maybe even more important -- does it do the correct calculations? 

I'm in particular puzzled about the lines 238 and 293.

First, `scr` is defined as $(\text{xFix}, \underbrace{0, \dots, 0}_{k \text{ entries}}).$

In the loop (starting in line 239), the last $k$ entries of `scr` are modified by setting it to the log prob of `obs` following some t-distribution plus a number (line 266). However, the first entries are never modified. Thus, equal `xFix` when exiting the loop.

Finally, in line 293, the sum of the entire vector -- not only the last k entires -- is calculated and I think we consider this the log score. I guess thats not what is want.

Additionally, I'm do not understand why `scr` and `xNew` should point at the same memory. In the loop, `scr` is modified which also changes  `xNew`. Now, depending on the values in `NN`, the code potentially feeds log-densities as arguments to the kernel function (line 248, 251, and 253).

**Comment by JCatwood** [comment]
Hi @wiep , thank you for raising the issue. I agree that `scr.sum()` should be changed to `scr[xFix.size(0):].sum()`.

`scr` and `xNew` sharing the same memory is probably not a great idea. We can change it. However, I believe that under the current conditioning structure, only one of `scr` and `xNew` will be used, i.e., they will not be used in the same call of `cond_samp`.

**Comment by wiep** [comment]
true, for mode sample xNew is never read.
